# SPRING CORE
spring:
  application:
    name: kotlin with spring-boot 2.0.0
# OUTPUT
  output:
    ansi:
      enabled: detect
# PROFILES
  profiles:
    active: dev
# DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 2
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
      log-condition-evaluation-delta: true

# EMBEDDED SERVER CONFIGURATION
server:
  servlet:
    context-path: /app
  port: 9000

logging:
  file: demo-kotlin-spring2.log
  level:
    root: INFO
    org.springframework: INFO
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
#    org.springframework.transaction: TRACE
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.transaction: DEBUG
#    org.hibernate.jpa.internal: DEBUG
#    org.hibernate.event.internal: DEBUG
#    org.hibernate.engine.transaction.internal: DEBUG
#    org.hibernate.internal.util: DEBUG
    com.example.demokotlin2: DEBUG

my-app:
  my-module:
    foo:
      name: dummy
      min-height: 100
      max-height: 999
      color: green
      colors:
        - red
        - green
        - blue
      budget: 150
      parts:
        upper: TRUE
